services:
    ambta_doctrine_encrypt.orm_subscriber:
        class: Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%ambta_doctrine_encrypt.encryptor_class_name%", "%ambta_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }
    ambta_doctrine_encrypt.subscriber:
        alias: ambta_doctrine_encrypt.orm_subscriber
    ambta_doctrine_encrypt.encryptor:
        class: Ambta\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%ambta_doctrine_encrypt.encryptor_class_name%"
            - "%ambta_doctrine_encrypt.secret_key%"
